project_name: "mlops_house_price_prediction"

data_paths:
  raw_data_path: "data/raw/kc_house_data.csv"
  processed_data_path: "data/processed/kc_house_data_processed.csv"

target_column: "price"

great_expectations:
  suite_name: "kc_house_raw"
  datasource_name: "kc_house_datasource"
  data_asset_name: "kc_house_data"
