# configs/config.yaml
data:
  raw_data_path: "data/raw/house_prices.csv"
  processed_data_path: "data/processed/features.parquet"
  target_column: "SalePrice"

model:
  name: "GradientBoostingRegressor"
  params:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3

mlflow:
  tracking_uri: "file:./mlruns" # Local MLflow tracking server

great_expectations:
  base_path: "great_expectations"

dvc:
  cache_dir: ".dvc/cache"

server:
  host: "0.0.0.0"
  port: 8000
